[project]
name = "ict-auth"
version = "2.0.0"
description = "使用 CLI 进行中科院计算所上网认证登陆"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "playwright>=1.48.0",
    "typer>=0.15.4",
]

[project.scripts]
ict_auth = "ict_auth.cli:run"
