name: Build

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          ./package.sh

      - name: Release
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ict_auth.run
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
