name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit info
        run: |
          COMMIT_DATE=$(git log -1 --format=%cd --date=format:'%Y-%m-%d')
          echo "$COMMIT_DATE" > src/release.txt

      - name: Build
        run: |
          ./build.sh

      - name: Test
        run: |
          chmod +x ./ict_auth.run
          echo "y" | ./ict_auth.run
          python3 test.py

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ict_auth.run
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true

      - name: Upload R2
        if: startsWith(github.ref, 'refs/tags/')
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: ict_auth.run
          destination-dir: ./