name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          ./package.sh
          chmod +x ./ict_auth.run
          echo "y" | ./ict_auth.run
          python3 test.py

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ict_auth.run
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
