name: Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          bash ./pack.sh

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ict_auth.run
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
        